name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
      - "master"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt' # See 'Supported distributions' for available options

      - name: Build Eureka Naming Server Docker Image
        working-directory: ./service-registry-with-eureka/naming-server/naming-server
        run: |
          mvn clean package -DskipTests
          docker build -t garibaldii/naming-server:0.0.1-SNAPSHOT .

      - name: Build Api Gateway Docker Image
        working-directory: ./service-registry-with-eureka/api-gateway
        run: |
          mvn clean package -DskipTests
          docker build -t garibaldii/api-gateway:0.0.1-SNAPSHOT .

      - name: Build Book Service Docker Image
        working-directory: ./service-registry-with-eureka/ms/book-service
        run: |
          mvn clean package -DskipTests
          docker build -t garibaldii/book-service:latest .

      - name: Build Exchange Service Docker Image
        working-directory: ./service-registry-with-eureka/ms/exchange-service
        run: |
          mvn clean package -DskipTests
          docker build -t garibaldii/exchange-service:latest .     

      - name: Docker Compose Build
        working-directory: ./service-registry-with-eureka
        run: docker compose build

      - name: Tag Docker Images
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/naming-server:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/naming-server:latest
          docker tag ${{secrets.DOCKER_USERNAME}}/naming-server:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/naming-server:${{github.RUN_ID}}
          
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/api-gateway:latest
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.RUN_ID}}
          
          docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}
          
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}

      - name: Push Docker Images to Docker hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/naming-server:latest
          docker push ${{secrets.DOCKER_USERNAME}}/naming-server:${{github.RUN_ID}}
          
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:latest
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.RUN_ID}}
          
          docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}
          
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}